package principal;

import DB.Constantes;
import DB.codigoTableModel;
import DB.DataBase;
import DB.cotacaoTableModel;
import DB.monitorarCotacao;
import java.sql.PreparedStatement;
import parserhtml.ParserInformacoesDasAcoes;

public class incluirCodigo extends javax.swing.JFrame {
    private static boolean unicaInstancia = false;
    private codigoTableModel tbmCodigo;
    private final cotacaoTableModel tbmCotacao;
    private final DataBase dataBase;
    private String sql;
    private PreparedStatement ps;
    private String codigo;
    private ParserInformacoesDasAcoes informacao;
    
    public incluirCodigo(DataBase db, cotacaoTableModel tbm) {
        initComponents();
        unicaInstancia = true;
        dataBase = db;        
        tbmCotacao = tbm;
        informacao = new ParserInformacoesDasAcoes();
        
        atualizar();
    }
         
    public void addCodigo() {
        monitorarCotacao m = new monitorarCotacao();
        m.setCodigo(codigo);
        m.setValor(0.0f);
        m.setVariacao(0.0f);
        m.setData(Calendario.getDataAtual());
        tbmCotacao.addCotacao(m);
    }
        
    public final void atualizar() {
        sql = "SELECT * FROM APP.Codigo ORDER BY Codigo";
        tbmCodigo = new codigoTableModel(dataBase,sql);
        
        jTableCodigo.setModel(tbmCodigo);     
        limpar();
    }
    
    public void limpar() {
        IdCodigo.setText("");
        Codigo.setText("");
        Descricao.setText("");
    }
    
    public static boolean isInstaciada() {
        return unicaInstancia;
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IdCodigo = new javax.swing.JTextField();
        Codigo = new javax.swing.JTextField();
        Descricao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCodigo = new javax.swing.JTable();
        jButtonIncluirCodigo = new javax.swing.JButton();
        jButtonExcluirCodigo = new javax.swing.JButton();
        jButtonAlterarCodigo = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Inclusão de Códigos");
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciamento dos códigos das ações");

        jLabel2.setText("ID");

        jLabel3.setText("Código");

        jLabel4.setText("Descrição");

        jTableCodigo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCodigoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCodigo);

        jButtonIncluirCodigo.setText("Incluir");
        jButtonIncluirCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirCodigoActionPerformed(evt);
            }
        });

        jButtonExcluirCodigo.setText("Excluir");
        jButtonExcluirCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirCodigoActionPerformed(evt);
            }
        });

        jButtonAlterarCodigo.setText("Alterar");
        jButtonAlterarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarCodigoActionPerformed(evt);
            }
        });

        jButton4.setText("Monitorar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Descricao))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(IdCodigo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonIncluirCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluirCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterarCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(11, 11, 11))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IdCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIncluirCodigo)
                    .addComponent(jButtonExcluirCodigo)
                    .addComponent(jButtonAlterarCodigo)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCodigoMouseClicked
        int linhaSelecionada = jTableCodigo.getSelectedRow();
        IdCodigo.setText(tbmCodigo.getValueAt(linhaSelecionada, 0).toString());
        Codigo.setText(tbmCodigo.getValueAt(linhaSelecionada, 1).toString());
        Descricao.setText(tbmCodigo.getValueAt(linhaSelecionada, 2).toString());
    }//GEN-LAST:event_jTableCodigoMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        for(int i: jTableCodigo.getSelectedRows()) {
            int linhaSelecionada = i;
            int id_codigo = (int)tbmCodigo.getValueAt(linhaSelecionada, Constantes.COLUNA_ID_CODIGO);
            codigo = tbmCodigo.getValueAt(linhaSelecionada, Constantes.COLUNA_CODIGO_CODIGO).toString();
            boolean achei = false;
            for(int linha = 0; linha <= tbmCotacao.getRowCount(); linha++) {
                if(tbmCotacao.getValueAt(linha, Constantes.COLUNA_CODIGO_COTACAO).toString().equalsIgnoreCase(codigo)) {
                    achei = true;
                    break;
                }
            }       

            sql = "INSERT INTO APP.COTACAO (ID_COTACAO, ID_CODIGO, VALOR_FECHAMENTO, DATA) VALUES(" + 
                    (dataBase.maiorID("ID_COTACAO","COTACAO") + 1) +
                    "," + id_codigo +
                    "," + 0.0 +
                    ",DATE('" + Calendario.getDataAtualDerbyDB() + "'))";                                       

            if(achei == false) {
                dataBase.executeUpdateSQL(sql);

                addCodigo(); // Adiciona o código na tabela de monitoramento de ações
                //tbmCotacao.atualizaLista();
            } else {
                System.out.println("Código já listado!");
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonAlterarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarCodigoActionPerformed
        sql = "UPDATE APP.Codigo SET ID_CODIGO=" + IdCodigo.getText() + ", CODIGO='" + Codigo.getText() + "', DESCRICAO='"+ Descricao.getText() + "' WHERE ID_CODIGO=" + IdCodigo.getText();
               
        dataBase.executeUpdateSQL(sql);
        atualizar();
    }//GEN-LAST:event_jButtonAlterarCodigoActionPerformed

    private void jButtonExcluirCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirCodigoActionPerformed
        int linhaSelecionada = jTableCodigo.getSelectedRow();
        sql = "DELETE FROM APP.Codigo WHERE ID_CODIGO=" + tbmCodigo.getValueAt(linhaSelecionada, 0);

        dataBase.executeUpdateSQL(sql);
        atualizar();
    }//GEN-LAST:event_jButtonExcluirCodigoActionPerformed

    private void jButtonIncluirCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirCodigoActionPerformed
        sql = "INSERT INTO APP.Codigo (ID_CODIGO, CODIGO, DESCRICAO) VALUES(" + (dataBase.maiorID("ID_CODIGO","CODIGO") + 1) + ",'" + Codigo.getText() + "','" + Descricao.getText() + "')";
        
        dataBase.executeUpdateSQL(sql);
        atualizar();                
    }//GEN-LAST:event_jButtonIncluirCodigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpar();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Codigo;
    private javax.swing.JTextField Descricao;
    private javax.swing.JTextField IdCodigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAlterarCodigo;
    private javax.swing.JButton jButtonExcluirCodigo;
    private javax.swing.JButton jButtonIncluirCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCodigo;
    // End of variables declaration//GEN-END:variables
}
