package principal;
import DB.Constantes;
import DB.DataBase;
import DB.compraTableModel;
import DB.cotacaoTableModel;
import DB.monitorarCotacao;
import DB.mudarCorPreco;
import java.awt.MouseInfo;

public class Main extends javax.swing.JFrame {
    private incluirCodigo janelaCodigo;
    private formCompra janelaCompra;
    private formImportarCotacao janelaImportarCotacao;
    private final DataBase db;
    private cotacaoTableModel tbmCotacao;
    private compraTableModel tbmCompra;
    private String sql;
    private Calendario cal;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();         
        this.setLocationRelativeTo(null);
                
        cal = new Calendario();
        
        db = new DataBase();
        db.conectar(true);        
         
        //db.calcularMediaMovelSimples("CSAN3", 3);
        //System.exit(0);
        
        mudarCorPreco mudaCor = new mudarCorPreco();        
        jTableCotacao.setDefaultRenderer(Object.class, mudaCor); 
        jTableCotacao.addMouseListener(new menuPopCotacao(jPopupMenuPapeis));
        //jTableCotacao.setAutoCreateRowSorter(true);
        
//        jTableCompra.addMouseListener(new menuPopCotacao(jPopupMenuComprados));
        
        atualizar();
    }

    private void atualizar() {        
        // Cotação
        //sql = "SELECT CODIGO.CODIGO as A, COTACAO.VALOR_FECHAMENTO, COTACAO.DATA FROM APP.CODIGO CODIGO, APP.COTACAO COTACAO WHERE COTACAO.ID_CODIGO = CODIGO.ID_CODIGO";
        sql = "SELECT CODIGO, VALOR_FECHAMENTO,VOLUME,DATA \n" +
                "FROM APP.COTACAOHISTORICA\n" +
                "WHERE DATA = (select MAX(data) from app.COTACAOHISTORICA)";
        
        db.executeSQL(sql);                
        tbmCotacao = new cotacaoTableModel(db.cotacaoList(), db);        
        jTableCotacao.setModel(tbmCotacao);         
        
        // Compras
//        sql = "SELECT * FROM APP.COMPRA";
//        db.executeSQL(sql);
//        tbmCompra = new compraTableModel(db.compraList(), db);
//        jTableCompra.setModel(tbmCompra);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuPapeis = new javax.swing.JPopupMenu();
        Excluir = new javax.swing.JMenuItem();
        IncluirCodigo = new javax.swing.JMenuItem();
        Comprar = new javax.swing.JMenuItem();
        jPopupMenuComprados = new javax.swing.JPopupMenu();
        excluirComprado = new javax.swing.JMenuItem();
        venderComprado = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCotacao = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCompra = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemGerenciarCodigo = new javax.swing.JMenuItem();
        jMenuItemImportarCotacao = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        Excluir.setLabel("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        jPopupMenuPapeis.add(Excluir);

        IncluirCodigo.setLabel("Incluir Papeis");
        IncluirCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncluirCodigoActionPerformed(evt);
            }
        });
        jPopupMenuPapeis.add(IncluirCodigo);

        Comprar.setText("Comprar");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });
        jPopupMenuPapeis.add(Comprar);

        excluirComprado.setText("Excluir");
        excluirComprado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCompradoActionPerformed(evt);
            }
        });
        jPopupMenuComprados.add(excluirComprado);

        venderComprado.setText("Vender");
        jPopupMenuComprados.add(venderComprado);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jToolBar2.setBorder(null);
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jButton1.setText("Limpar Cotação");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jTableCotacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCotacao);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Papeis", jPanel1);

        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        jTableCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCompra);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comprados", jPanel2);

        jMenu1.setText("Arquivo");

        jMenuItemGerenciarCodigo.setText("Gerenciar Código");
        jMenuItemGerenciarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarCodigoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemGerenciarCodigo);

        jMenuItemImportarCotacao.setText("Importar Cotação");
        jMenuItemImportarCotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportarCotacaoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemImportarCotacao);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGerenciarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarCodigoActionPerformed
        if(!incluirCodigo.isInstaciada()) {
            janelaCodigo = new incluirCodigo(db, tbmCotacao);              
        } 
        janelaCodigo.atualizar();
        janelaCodigo.setVisible(true);  
    }//GEN-LAST:event_jMenuItemGerenciarCodigoActionPerformed

    /* 
        Menu POPUP, comando Excluir
    */
    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        int linhaSeleciona = jTableCotacao.getSelectedRow();
                        
        db.removerCotacao(tbmCotacao.getValueAt(linhaSeleciona, Constantes.COLUNA_CODIGO_COTACAO).toString());
        
        tbmCotacao.removeCotacao(linhaSeleciona);
    }//GEN-LAST:event_ExcluirActionPerformed

    private void IncluirCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncluirCodigoActionPerformed
        if(!incluirCodigo.isInstaciada()) {
            janelaCodigo = new incluirCodigo(db, tbmCotacao);              
        } 
        janelaCodigo.atualizar();
        janelaCodigo.setVisible(true);  
    }//GEN-LAST:event_IncluirCodigoActionPerformed

    /**
     * Comando comprar do menu popup
     * @param evt 
     */
    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        int linhaSeleciona = jTableCotacao.rowAtPoint(menuPopCotacao.getPosicao());
        
        jTableCotacao.setRowSelectionInterval(linhaSeleciona, linhaSeleciona);
        monitorarCotacao cotacao = tbmCotacao.getCotacao(linhaSeleciona);
        
        if(!formCompra.isInstaciada()) {
            janelaCompra = new formCompra(db, cotacao);                          
        }         
               
        int x = (int) MouseInfo.getPointerInfo().getLocation().getX();
        int y = (int) MouseInfo.getPointerInfo().getLocation().getY();
        janelaCompra.setJTableModel(tbmCompra);
        janelaCompra.setJTable(jTableCompra);
        janelaCompra.setDataBase(db);
        janelaCompra.setCotacao(cotacao);
        janelaCompra.setLocation(x - (janelaCompra.getWidth()/2), y - (janelaCompra.getHeight() / 2));        
        janelaCompra.setVisible(true);        
        
    }//GEN-LAST:event_ComprarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        db.desconectar();
    }//GEN-LAST:event_formWindowClosed

    private void excluirCompradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCompradoActionPerformed
        int linhaSeleciona = jTableCompra.getSelectedRow();
                        
        db.removerCompra(tbmCompra.getValueAt(linhaSeleciona, Constantes.COLUNA_CODIGO_COMPRA).toString());
        
        tbmCompra.removeCompra(linhaSeleciona);
    }//GEN-LAST:event_excluirCompradoActionPerformed

    private void jMenuItemImportarCotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportarCotacaoActionPerformed
       // if(!incluirCodigo.isInstaciada()) {
            janelaImportarCotacao = new formImportarCotacao();              
       // } 
        janelaImportarCotacao.setDataBase(db);
        janelaImportarCotacao.setVisible(true);  
    }//GEN-LAST:event_jMenuItemImportarCotacaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        db.executeUpdateSQL("DELETE FROM APP.COTACAO");
        atualizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Comprar;
    private javax.swing.JMenuItem Excluir;
    private javax.swing.JMenuItem IncluirCodigo;
    private javax.swing.JMenuItem excluirComprado;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemGerenciarCodigo;
    private javax.swing.JMenuItem jMenuItemImportarCotacao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenuComprados;
    private javax.swing.JPopupMenu jPopupMenuPapeis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCompra;
    private javax.swing.JTable jTableCotacao;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JMenuItem venderComprado;
    // End of variables declaration//GEN-END:variables
}
